#Class variable is defined outside any method in contrast the instance variable which it is defines for every objecto of the class
#With class methods, it only works with class variables. The factory method gives an alternative way to initialize instances by a list, dict...
